sudo: false
language: go
go:
- 1.7.x
- 1.8.x
- 1.9.x
- 1.10.x
script:
- tar zxvf keys.tar.gz
- go test -v ./... -cover
before_install:
- openssl aes-256-cbc -K $encrypted_3bab0e510ecf_key -iv $encrypted_3bab0e510ecf_iv
  -in keys.tar.gz.enc -out keys.tar.gz -d
env:
- GOOGLE_APPLICATION_CREDENTIALS=service-account-key.json
