sudo: false
language: go
go:
- 1.6.x
- 1.7.x
- 1.8.x
- 1.9.x
- 1.10.x
- master
script:
- tar zxvf keys.tar.gz
before_install:
- openssl aes-256-cbc -K $encrypted_ddd1d904a899_key -iv $encrypted_ddd1d904a899_iv
  -in keys.tar.gz.enc -out .\\keys.tar.gz -d
env:
- GOOGLE_APPLICATION_CREDENTIALS=.\\service-account-key.json
